In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

In [2]:
# Import the API key.
from config import gog_key

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/weatherpy_challenge.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Descrption,Rain inches (last 3 hours),Snow inches (last 3 hours)
0,0,Hithadhoo,MV,2020-01-04 20:50:47,-0.60,73.08,83.03,68,99,4.38,overcast clouds,0.0,0.0
1,1,Khatanga,RU,2020-01-04 21:02:45,71.98,102.47,-18.11,85,0,8.79,clear sky,0.0,0.0
2,2,Malyn,UA,2020-01-04 21:03:00,50.77,29.25,35.60,93,100,6.71,overcast clouds,0.0,0.0
3,3,Lovington,US,2020-01-04 21:03:00,32.94,-103.35,61.00,22,5,10.29,clear sky,0.0,0.0
4,4,Talnakh,RU,2020-01-04 21:03:00,69.49,88.39,-2.20,84,100,20.13,overcast clouds,0.0,0.0

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=gog_key)

In [5]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain_ans = str(input("Do you want it to be raining? (yes/no) "))
snow_ans = str(input("Do you want it to be snowing? (yes/no) "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) yes
Do you want it to be snowing? (yes/no) no

In [6]:
# Filter the dataset to find the cities that fit the criteria.
if rain_ans == 'yes' and snow_ans == 'yes':
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)& (city_data_df['Rain inches (last 3 hours)'] > 0 ) & (city_data_df['Snow inches (last 3 hours)'] > 0 ) ]
else:
    if rain_ans=='yes' and snow_ans =='no':
        preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)& (city_data_df['Rain inches (last 3 hours)'] > 0 ) & (city_data_df['Snow inches (last 3 hours)'] == 0 ) ]
    else:
            if rain_ans=='no' and snow_ans =='yes': 
               preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)& (city_data_df['Rain inches (last 3 hours)'] == 0 ) & (city_data_df['Snow inches (last 3 hours)'] > 0 ) ]
            else:
                   if rain_ans=='no' and snow_ans =='no':
                       preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)& (city_data_df['Rain inches (last 3 hours)'] == 0 ) & (city_data_df['Snow inches (last 3 hours)'] == 0 ) ]

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Descrption,Rain inches (last 3 hours),Snow inches (last 3 hours)
30,30,Kavieng,PG,2020-01-04 20:53:22,-2.57,150.80,83.77,77,100,12.12,moderate rain,4.88,0.0
64,64,Karratha,AU,2020-01-04 20:53:29,-20.74,116.85,83.57,73,100,17.98,light rain,1.00,0.0
67,67,Meulaboh,ID,2020-01-04 20:53:30,4.14,96.13,81.25,78,19,7.40,light rain,2.31,0.0
79,79,Isangel,VU,2020-01-04 20:50:23,-19.55,169.27,76.89,78,5,14.47,light rain,0.19,0.0
175,175,Baiao,BR,2020-01-04 20:53:55,-2.79,-49.67,80.49,84,99,4.09,light rain,1.63,0.0
197,197,Tual,ID,2020-01-04 20:51:53,-5.67,132.75,82.65,79,100,18.99,light rain,2.44,0.0
200,200,Wewak,PG,2020-01-04 20:54:00,-3.55,143.63,75.49,94,100,7.74,moderate rain,11.13,0.0
206,206,Biak,ID,2020-01-04 20:54:01,-0.91,122.88,81.61,79,100,13.47,moderate rain,4.50,0.0
214,214,Mahibadhoo,MV,2020-01-04 20:54:03,3.78,72.97,81.75,77,58,8.16,moderate rain,3.69,0.0
221,221,Omboue,GA,2020-01-04 20:54:05,-1.57,9.26,76.48,93,100,3.11,light rain,2.56,0.0

In [7]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng",'Current Descrption']].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp    Lat     Lng Current Descrption Hotel Name
30      Kavieng      PG     83.77  -2.57  150.80      moderate rain
64     Karratha      AU     83.57 -20.74  116.85         light rain
67     Meulaboh      ID     81.25   4.14   96.13         light rain
79      Isangel      VU     76.89 -19.55  169.27         light rain
175       Baiao      BR     80.49  -2.79  -49.67         light rain
197        Tual      ID     82.65  -5.67  132.75         light rain
200       Wewak      PG     75.49  -3.55  143.63      moderate rain
206        Biak      ID     81.61  -0.91  122.88      moderate rain
214  Mahibadhoo      MV     81.75   3.78   72.97      moderate rain
221      Omboue      GA     76.48  -1.57    9.26         light rain

In [8]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gog_key
}

In [9]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Current Descrption,Hotel Name
30,Kavieng,PG,83.77,-2.57,150.80,moderate rain,Nusa Island Retreat
64,Karratha,AU,83.57,-20.74,116.85,light rain,ibis Styles Karratha
67,Meulaboh,ID,81.25,4.14,96.13,light rain,Kost Pria
79,Isangel,VU,76.89,-19.55,169.27,light rain,Volcano Sea View Tree House
175,Baiao,BR,80.49,-2.79,-49.67,light rain,Hotel Eurosono
197,Tual,ID,82.65,-5.67,132.75,light rain,Grand Vilia Hotel
200,Wewak,PG,75.49,-3.55,143.63,moderate rain,In Wewak Boutique Hotel
206,Biak,ID,81.61,-0.91,122.88,moderate rain,Villa Mas Biak
214,Mahibadhoo,MV,81.75,3.78,72.97,moderate rain,Omadhoo Inn
221,Omboue,GA,76.48,-1.57,9.26,light rain,Hotel Olako

In [11]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description</dt><dd>{Current Descrption}</dd>
</dl>
"""

In [14]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [15]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Create the output file (CSV).
output_data_file = "weather_data/weatherpy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")